"""add chunked_at to documents

Revision ID: 3e591515042c
Revises: d279c865f6da
Create Date: 2026-08-08 00:09:20.198390
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e591515042c'
down_revision = 'd279c865f6da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('chunked_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_documents_chunked_at'), 'documents', ['chunked_at'], unique=False)
    # NOTE: l'autogénération détecte aussi des uq_*_id "manquants" sur
    # plusieurs tables (conversations, document_products, documents,
    # messages, products, roles, users) — artefact connu, sans rapport avec
    # cette migration (cf. migration d279c865f6da) : une UniqueConstraint sur
    # la même colonne que la PrimaryKeyConstraint ne se matérialise jamais
    # comme contrainte séparée sous Postgres. Volontairement exclu.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_chunked_at'), table_name='documents')
    op.drop_column('documents', 'chunked_at')
    # ### end Alembic commands ###
