"""add documents and document_products tables

Revision ID: d279c865f6da
Revises: 3e962970196b
Create Date: 2026-08-07 22:33:51.775086
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd279c865f6da'
down_revision = '3e962970196b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('file_type', sa.String(length=10), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('version', sa.String(length=30), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("category IN ('faq', 'manuals', 'procedures', 'products', 'videos')", name=op.f('ck_documents_category_valid')),
    sa.CheckConstraint("file_type IN ('pdf', 'docx', 'txt')", name=op.f('ck_documents_file_type_valid')),
    sa.CheckConstraint("status IN ('draft', 'published', 'archived')", name=op.f('ck_documents_status_valid')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_documents_created_by_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    sa.UniqueConstraint('id', name=op.f('uq_documents_id'))
    )
    op.create_index(op.f('ix_documents_category'), 'documents', ['category'], unique=False)
    op.create_index(op.f('ix_documents_created_by_id'), 'documents', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_index(op.f('ix_documents_title'), 'documents', ['title'], unique=False)
    op.create_table('document_products',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_products_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_document_products_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_products')),
    sa.UniqueConstraint('document_id', 'product_id', name='uq_document_product'),
    sa.UniqueConstraint('id', name=op.f('uq_document_products_id'))
    )
    op.create_index(op.f('ix_document_products_document_id'), 'document_products', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_products_product_id'), 'document_products', ['product_id'], unique=False)
    # NOTE: l'autogénération avait aussi détecté des contraintes uq_*_id
    # manquantes sur conversations/messages/products/roles/users (dérive
    # préexistante, sans rapport avec cette migration) — volontairement
    # exclues d'ici pour ne pas modifier des tables hors périmètre.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_products_product_id'), table_name='document_products')
    op.drop_index(op.f('ix_document_products_document_id'), table_name='document_products')
    op.drop_table('document_products')
    op.drop_index(op.f('ix_documents_title'), table_name='documents')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_created_by_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_category'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
