"""add tickets table

Revision ID: e168dfe1c65a
Revises: 3db91fb53553
Create Date: 2026-08-14 19:26:54.137957
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e168dfe1c65a'
down_revision = '3db91fb53553'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('assigned_technician_id', sa.UUID(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('open', 'in_progress', 'resolved', 'closed')", name=op.f('ck_tickets_status_valid')),
    sa.ForeignKeyConstraint(['assigned_technician_id'], ['users.id'], name=op.f('fk_tickets_assigned_technician_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], name=op.f('fk_tickets_client_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_tickets_conversation_id_conversations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_tickets_product_id_products'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tickets')),
    sa.UniqueConstraint('id', name=op.f('uq_tickets_id'))
    )
    op.create_index(op.f('ix_tickets_assigned_technician_id'), 'tickets', ['assigned_technician_id'], unique=False)
    op.create_index(op.f('ix_tickets_client_id'), 'tickets', ['client_id'], unique=False)
    op.create_index(op.f('ix_tickets_conversation_id'), 'tickets', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_tickets_product_id'), 'tickets', ['product_id'], unique=False)
    op.create_index(op.f('ix_tickets_status'), 'tickets', ['status'], unique=False)
    # NOTE: l'autogénération a aussi redétecté les contraintes uq_*_id
    # manquantes sur conversations/document_products/documents/messages/
    # products/roles/users (même dérive préexistante déjà signalée dans
    # d279c865f6da) — volontairement exclues d'ici, hors périmètre de cette
    # migration (ajout de la table tickets uniquement).
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_status'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_product_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_conversation_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_client_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_assigned_technician_id'), table_name='tickets')
    op.drop_table('tickets')
    # ### end Alembic commands ###
